//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SMSEntities : DbContext
    {
        public SMSEntities()
            : base("name=SMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GuardianInfo> GuardianInfoes { get; set; }
        public virtual DbSet<ParentInfo> ParentInfoes { get; set; }
        public virtual DbSet<SetupBlock> SetupBlocks { get; set; }
        public virtual DbSet<SetupClass> SetupClasses { get; set; }
        public virtual DbSet<SetupSection> SetupSections { get; set; }
        public virtual DbSet<SetupSubject> SetupSubjects { get; set; }
        public virtual DbSet<StudentClassInfo> StudentClassInfoes { get; set; }
        public virtual DbSet<StudentInfo> StudentInfoes { get; set; }
    }
}
