//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentInfo()
        {
            this.GuardianInfoes = new HashSet<GuardianInfo>();
            this.ParentInfoes = new HashSet<ParentInfo>();
            this.StudentClassInfoes = new HashSet<StudentClassInfo>();
        }
    
        public int StudentId { get; set; }
        public string FirstName { get; set; }
        public string PState { get; set; }
        public string PDistrict { get; set; }
        public string PMetropolitan { get; set; }
        public string PSubMetropolitan { get; set; }
        public string PMunicipality { get; set; }
        public string PGauPalika { get; set; }
        public string PWardNo { get; set; }
        public string TState { get; set; }
        public string TDistrict { get; set; }
        public string TMetropolitan { get; set; }
        public string TSubMetropolitan { get; set; }
        public string TMunicipality { get; set; }
        public string TGauPalika { get; set; }
        public string TWardNo { get; set; }
        public string BloodGroup { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string EmailId { get; set; }
        public Nullable<long> CellNumber { get; set; }
        public string Gender { get; set; }
        public string ImageName { get; set; }
        public string ImagePath { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public string MidName { get; set; }
        public string LastName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GuardianInfo> GuardianInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParentInfo> ParentInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentClassInfo> StudentClassInfoes { get; set; }
    }
}
